# ESP32-C3 Luatos CORE-ESP32
# https://wiki.luatos.org/chips/esp32c3/board.html

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

output:
  - platform: gpio
    id: output_onboard_led
    pin:
      number: 12
      # https://github.com/esphome/issues/issues/3744
      ignore_pin_validation_error: true

status_led:
  pin:
    number: 13
    # https://github.com/esphome/issues/issues/3744
    ignore_pin_validation_error: true
