# Luatos ESP32-C3 Core
# https://wiki.luatos.org/chips/esp32c3/board.html

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: airm2m_core_esp32c3
  framework:
    type: esp-idf

output:
  - platform: gpio
    id: output_onboard_led
    pin:
      number: 12

status_led:
  pin: 13
