# C3V2 (ESP32-C3 Super Mini)
# https://www.espboards.dev/esp32/esp32-c3-super-mini/
#
#
# Управляемые объекты:
#   - Одноцветный светодиод (обычный)   (output.mono_led)
#   - Ключ (кнопка)                     (binary_sensor.key)
# Неуправляемые объекты:
#   - нет
# + разные пины

substitutions:
  friendly_board_name: "C3V2"

  # Использовать одноцветный светодиод?
  use_mono_led: false
  # Использовать ключ?
  use_key: false

  # Одноцветный светодиод (обычный)
  mono_led: !include
    file: int/output/mono_led.yaml
    vars:
      pin:
        number: 8
        inverted: true
        ignore_strapping_warning: true

  # Ключ (кнопка)
  key: !include
    file: int/binary_sensor/key.yaml
    vars:
      pin:
        number: 9
        inverted: true
        ignore_strapping_warning: true
        mode:
          input: true
          pullup: true

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

packages:
  # Одноцветный светодиод (обычный)
  mono_led: ${ mono_led if use_mono_led else {} }

  # Ключ (кнопка)
  key: ${ key if use_key else {} }
