# IL1 (ESP32-C3 Ivanych Light 1)
# На основе отладочной платы ESP32-C3 Super Mini
# https://www.espboards.dev/esp32/esp32-c3-super-mini/
#
# Управляемые объекты:
#   - Одноцветный светодиод (обычный)   (output.mono_led)
#   - Ключ (кнопка)                     (binary_sensor.key)
#   - Пульсометр (фотодиод)             (sensor.pulsometer)
#   - Счётчик импульсов (фотодиод)      (sensor.pulsometer_N_total)
# Неуправляемые объекты:
#   - нет
# + разные пины

substitutions:
  friendly_board_name: "IL1"

  # Использовать одноцветный светодиод?
  use_mono_led: false
  # Использовать ключ?
  use_key: false
  # Использовать пульсометр?
  use_pulsometer: false

  # Одноцветный светодиод (обычный)
  mono_led: !include
    file: int/output/mono_led.yaml
    vars:
      pin:
        number: 8
        inverted: true
        ignore_strapping_warning: true

  # Ключ (кнопка)
  key: !include
    file: int/binary_sensor/key.yaml
    vars:
      pin:
        number: 9
        inverted: true
        ignore_strapping_warning: true
        mode:
          input: true
          pullup: true

  # Пульсометр (фотодиод)
  pulsometer: !include
    file: int/sensor/pulsometer.yaml
    vars:
      pin:
        number: 5
        inverted: true
        mode:
          input: true
          pullup: true

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

packages:
  # Одноцветный светодиод
  mono_led: ${ mono_led if use_mono_led else {} }

  # Ключ
  key: ${ key if use_key else {} }

  # Пульсометр
  pulsometer: ${ pulsometer if use_pulsometer else {} }
