# ESP32-C3 Super Mini
# https://www.espboards.dev/esp32/esp32-c3-super-mini/
#
# Управляемые объекты:
#   - Светодиод  (output_led)
#   - Кнопка     (binary_sensor_button)
# Неуправляемые объекты:
#   - нет
# + разные пины

substitutions:
  friendly_board_name: "M1"
  debounce_delay: 30ms

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

packages:
  # Светодиод
  output_led: !include
    file: int/output_led.yaml
    vars:
      pin:
        number: 8
        inverted: true

  # Кнопка
  binary_sensor_button: !include
    file: int/binary_sensor_button.yaml
    vars:
      pin:
        number: 9
        inverted: true
