# ESP32-C3 Super Mini
# https://duino.ru/esp32-c3/
#
# Управляемые объекты (интерфейс BUTTON1):
#   - Кнопка на плате      (binary_sensor_onboard_button)
#   - Светодиод на плате   (output_onboard_led)
# + разные пины

substitutions:
  board_name: "m1"
  debounce_delay: 30ms

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

output:
  # Светодиод на плате
  - platform: gpio
    id: output_onboard_led
    pin:
      number: 8
      inverted: true

binary_sensor:
  # Кнопка на плате
  - platform: gpio
    name: "Onboard button"
    id: binary_sensor_onboard_button
    pin:
      number: 9
      inverted: true
    filters:
      - delayed_on: ${debounce_delay}
