# ESP32-S NodeMCU-32S
# https://wiki.geekworm.com/NodeMCU-32S
#
# Управляемые объекты:
#   - Кнопка     (binary_sensor_button)
#   - Светодиод  (output_led)
# Неуправляемые объекты:
#   - нет
# + разные пины

substitutions:
  board_name: "n1"
  friendly_board_name: "N1"
  debounce_delay: 30ms

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

binary_sensor:
  # Кнопка
  - platform: gpio
    name: "Button"
    id: binary_sensor_button
    pin:
      number: 0
      inverted: true
    filters:
      - delayed_on: ${debounce_delay}

output:
  # Светодиод
  - platform: gpio
    id: output_led
    pin:
      number: 2
