# S1V1 (ESP32 30-Pin DevKit)
# https://www.espboards.dev/esp32/esp32-30pin-devkit-generic/
#
#
# Управляемые объекты:
#   - Одноцветный светодиод (обычный)   (output.mono_led)
#   - Ключ (кнопка)                     (binary_sensor.key)
# Неуправляемые объекты:
#   - нет
# + разные пины

substitutions:
  friendly_board_name: "S1V1"

  # Использовать одноцветный светодиод?
  mono_led: false
  # Использовать ключ?
  key: false

  # Одноцветный светодиод (обычный)
  exposed_mono_led: !include
    file: int/output/mono_led.yaml
    vars:
      pin:
        number: 2
        ignore_strapping_warning: true

  # Ключ (кнопка)
  exposed_key: !include
    file: int/binary_sensor/key.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true

esp32:
  variant: esp32
  framework:
    type: esp-idf

packages:
  # Одноцветный светодиод (обычный)
  mono_led: ${ exposed_mono_led if mono_led else {} }

  # Ключ (кнопка)
  key: ${ exposed_key if key else {} }
