# ESP32 30-Pin DevKit (Generic Clone)
# https://www.espboards.dev/esp32/esp32-30pin-devkit-generic/
#
# Управляемые объекты:
#   - Светодиод     (output_led)
#   - Кнопка        (binary_sensor_button)
# Неуправляемые объекты:
#   - нет
# + разные пины

substitutions:
  friendly_board_name: "S1V1"

esp32:
  variant: esp32
  framework:
    type: esp-idf

packages:
  # Светодиод
  output_led: !include
    file: int/output_led.yaml
    vars:
      pin:
        number: 2

  # Кнопка
  binary_sensor_button: !include
    file: int/binary_sensor_button.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true
