# S1V2 (ESP32-CAM OV2640)
# https://www.espboards.dev/esp32/esp32cam/
# https://randomnerdtutorials.com/esp32-cam-ai-thinker-pinout/
#
# Управляемые объекты:
#   - Индикатор                         (ligh_indicator)
#   - Подсветка                         (ligh_flash)
#   - Кнопка                            (binary_sensor_button)
#   - Камера                            (esp32_camera)
# Неуправляемые объекты:
#   - Статусный индикатор
# + разные пины

substitutions:
  friendly_board_name: "S1V2"

esp32:
  variant: esp32
  framework:
    type: esp-idf

# I2C
i2c:
  # Идентификатор "i2c_1" — дефолтное значение, используемое в интерфейсах,
  # использующих шину I2C
  - id: i2c_1
    sda: 26
    scl: 27

# Память PSRAM
psram:
  mode: quad
  speed: 80MHz

packages:
  # Индикатор (бинарный светодиод)
  indicator: !include
    file: int/light_indicator/binary_led.yaml
    vars:
      pin:
        number: 33
        inverted: true

  # Статусный индикатор (совмещённый с индикатором)
  status: !include
    file: int/light_status/light_indicator.yaml

  # Подсветка (одноцветный светодиод)
  flash: !include
    file: int/light_flash/mono_led.yaml
    vars:
      pin:
        number: 4

  # Кнопка
  binary_sensor_button: !include
    file: int/binary_sensor_button.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true

  # Камера (стандартная камера)
  camera: !include
    file: int/esp32_camera/esp32_camera.yaml
    vars:
      data_pins:
        # Пин 5 — strapping
        - number: 5
          ignore_strapping_warning: true
        - 18
        - 19
        - 21
        - 36
        - 39
        - 34
        - 35
      vsync_pin: 25
      href_pin: 23
      external_clock:
        # Пин 0 — strapping, и тут будет варнинг,
        # но ignore_strapping_warning тут почему-то не срабатывает,
        # как будто в этом месте этот флаг игнорируется.
        pin:
          number: 0
          ignore_strapping_warning: true
        frequency: 12MHz
      pixel_clock_pin: 22

# На S1V2 у камеры есть дополнительный пин
esp32_camera:
  power_down_pin: 32
