# S1V2 (ESP32-CAM OV2640)
# https://www.espboards.dev/esp32/esp32cam/
# https://randomnerdtutorials.com/esp32-cam-ai-thinker-pinout/
#
# Управляемые объекты:
#   - Одноцветный светодиод 1 (обычный) (output.mono_led)
#   - Одноцветный светодиод 2 (яркий)   (output.mono_led)
#   - Ключ (кнопка)                     (binary_sensor.key)
#   - Камера (стандартная камера)       (esp32_camera)
# Неуправляемые объекты:
#   - нет
# + разные пины

substitutions:
  friendly_board_name: "S1V2"

  # Использовать ключ?
  key: false
  # Использовать камеру?
  esp32_camera: false

  # Ключ (кнопка)
  exposed_key: !include
    file: int/binary_sensor/key.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true

  # Камера (стандартная камера)
  exposed_esp32_camera: !include
    file: int/esp32_camera/esp32_camera.yaml
    vars:
      data_pins:
        # Пин 5 — strapping
        - number: 5
          ignore_strapping_warning: true
        - 18
        - 19
        - 21
        - 36
        - 39
        - 34
        - 35
      vsync_pin: 25
      href_pin: 23
      external_clock:
        # Пин 0 — strapping, и тут будет варнинг,
        # но ignore_strapping_warning тут почему-то не срабатывает,
        # как будто в этом месте этот флаг игнорируется.
        pin:
          number: 0
          ignore_strapping_warning: true
        frequency: 12MHz
      pixel_clock_pin: 22
      # На S1V2 у камеры есть опциональный пин power_down_pin
      power_down_pin: 32

esp32:
  variant: esp32
  framework:
    type: esp-idf

# I2C
i2c:
  # Идентификатор "i2c_1" — дефолтное значение, используемое в интерфейсах,
  # использующих шину I2C
  - id: i2c_1
    sda: 26
    scl: 27

# Память PSRAM
psram:
  mode: quad
  speed: 80MHz

packages:
  # Одноцветный светодиод 1 (обычный)
  mono_led: !include
    file: int/output/mono_led.yaml
    vars:
      pin:
        number: 33
        inverted: true

  # Одноцветный светодиод 2 (яркий)
  mono_led_2: !include
    file: int/output/mono_led.yaml
    vars:
      number: 2
      pin:
        number: 4

  # Ключ (кнопка)
  key: ${ exposed_key if key else {} }

  # Камера (стандартная камера)
  esp32_camera: ${ exposed_esp32_camera if esp32_camera else {} }
