# S1V3 (ESP32 NodeMCU-32S)
# https://www.espboards.dev/esp32/nodemcu-32s/
#
#
# Управляемые объекты:
#   - Одноцветный светодиод (обычный)   (output.mono_led)
#   - Ключ (кнопка)                     (binary_sensor.key)
# Неуправляемые объекты:
#   - нет
# + разные пины

substitutions:
  friendly_board_name: "S1V3"

  # Использовать одноцветный светодиод?
  use_mono_led: false
  # Использовать ключ?
  use_key: false

  # Одноцветный светодиод
  mono_led: !include
    file: int/output/mono_led.yaml
    vars:
      pin:
        number: 2
        ignore_strapping_warning: true

  # Ключ
  key: !include
    file: int/binary_sensor/key.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true
        mode:
          input: true
          pullup: true

esp32:
  variant: esp32
  framework:
    type: esp-idf

packages:
  # Одноцветный светодиод
  mono_led: ${ mono_led if use_mono_led else {} }

  # Ключ
  key: ${ key if use_key else {} }
