# S3V1 (ESP32-S3 N16R8 CAM OV5640)
# https://www.oceanlabz.in/getting-started-with-esp32-s3-wroom-n16r8-cam-dev-board/
#
# Управляемые объекты:
#   - Индикатор                         (ligh_indicator)
#   - Подсветка                         (ligh_flash)
#   - Кнопка                            (binary_sensor_button)
#   - Камера                            (esp32_camera)
# Неуправляемые объекты:
#   - Статусный индикатор
# + разные пины

substitutions:
  friendly_board_name: "S3V1"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

# I2C
i2c:
  # Идентификатор "i2c_1" — дефолтное значение, используемое в интерфейсах,
  # использующих шину I2C
  - id: i2c_1
    sda: 4
    scl: 5

# Память PSRAM
psram:
  mode: octal
  speed: 80MHz

packages:
  # Индикатор (бинарный светодиод)
  indicator: !include
    file: int/light_indicator/binary_led.yaml
    vars:
      pin:
        number: 2

  # Статусный индикатор (совмещённый с индикатором)
  status: !include
    file: int/light_status/light_indicator.yaml

  # Подсветка (адресный светодиод)
  flash: !include
    file: int/light_flash/addr_led.yaml
    vars:
      pin:
        number: 48

  # Кнопка
  binary_sensor_button: !include
    file: int/binary_sensor_button.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true

  # Камера (стандартная камера)
  camera: !include
    file: int/esp32_camera/esp32_camera.yaml
    vars:
      data_pins: [ 11, 9, 8, 10, 12, 18, 17, 16 ]
      vsync_pin: 6
      href_pin: 7
      external_clock:
        pin:
          number: 15
        frequency: 12MHz
      pixel_clock_pin: 13
