# ESP32-S3 N16R8 CAM
# https://www.oceanlabz.in/getting-started-with-esp32-s3-wroom-n16r8-cam-dev-board/
#
# Управляемые объекты:
#   - Светодиод  (output_led)
#   - Кнопка     (binary_sensor_button)
# Неуправляемые объекты:
#   - Камера
# + разные пины

substitutions:
  friendly_board_name: "S3V1"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

# I2C
i2c:
  # Идентификатор "i2c_1" — дефолтное значение, используемое в интерфейсах,
  # использующих шину I2C
  - id: i2c_1
    sda: 4
    scl: 5

# Память PSRAM
psram:
  mode: octal
  speed: 80MHz

packages:
  # Светодиод
  output_led: !include
    file: int/output_led.yaml
    vars:
      pin:
        number: 2

  # Кнопка
  binary_sensor_button: !include
    file: int/binary_sensor_button.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true

  # Камера
  esp32_camera: !include
    file: int/esp32_camera.yaml
