# Sonoff DUALR3
# https://sonoff.tech/product/diy-smart-switches/dualr3/
#
# Управляемые объекты:
#   - Реле        (output_relay)          x2
#   - Кнопка      (binary_sensor_button)
#   - Выключатель (binary_sensor_switch)  x2
# Неуправляемые объекты:
#   - Статусный светодиод
#   - Ваттметр

substitutions:
  friendly_board_name: "SDR3"
  debounce_delay: 30ms

esp32:
  variant: esp32
  framework:
    type: esp-idf

packages:
  # Реле 1
  output_relay_1: !include
    file: int/output_relay.yaml
    vars:
      pin:
        number: 27

  # Реле 2
  output_relay_2: !include
    file: int/output_relay.yaml
    vars:
      number: 2
      pin:
        number: 14

  # Кнопка
  binary_sensor_button: !include
    file: int/binary_sensor_button.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true

  # Выключатель 1
  binary_sensor_switch_1: !include
    file: int/binary_sensor_switch.yaml
    vars:
      pin:
        number: 32
        inverted: true

  # Выключатель 2
  binary_sensor_switch_2: !include
    file: int/binary_sensor_switch.yaml
    vars:
      number: 2
      pin:
        number: 33
        inverted: true

  # Статусный светодиод
  status_led: !include
    file: int/status_led.yaml
    vars:
      pin:
        number: 13
        inverted: true

  # Ваттметр
  sensor_cse7766: !include
    file: int/sensor_cse7761.yaml

# UART для ваттметра
uart:
  tx_pin: 25
  rx_pin: 26
  baud_rate: 38400
  parity: EVEN
  stop_bits: 1
