# Sonoff MINIR4
# https://sonoff.tech/product/diy-smart-switches/minir4/
#
# Управляемые объекты:
#   - Реле        (output_relay)
#   - Светодиод   (output_led)
#   - Кнопка      (binary_sensor_button)
#   - Выключатель (binary_sensor_switch)
# Неуправляемые объекты:
#   - нет

substitutions:
  friendly_board_name: "SMR4"
  debounce_delay: 30ms

esp32:
  variant: esp32
  framework:
    type: esp-idf

packages:
  # Реле
  output_relay: !include
    file: int/output_relay.yaml
    vars:
      pin:
        number: 26

  # Светодиод
  output_led: !include
    file: int/output_led.yaml
    vars:
      pin:
        number: 19
        inverted: true

  # Кнопка
  binary_sensor_button: !include
    file: int/binary_sensor_button.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true

  # Выключатель
  binary_sensor_switch: !include
    file: int/binary_sensor_switch.yaml
    vars:
      pin:
        number: 27
        inverted: true
