# Sonoff MINIR4
# https://sonoff.tech/product/diy-smart-switches/minir4/

substitutions:
  board_name: "smr4"
  debounce_delay: 30ms

esp32:
  # На самом деле там ESP32-D0WD-V3, но esphome не знает про такую плату и выдаёт ошибку
  # Обсуждение - https://github.com/esphome/feature-requests/issues/2024
  # На devices.esphome.io указана плата esp32dev
  # https://devices.esphome.io/devices/Sonoff-MiniR4-Extreme
  board: esp32dev
  framework:
    type: arduino

output:
  - platform: gpio
    id: output_onboard_led
    pin:
      number: 19
      inverted: true

  - platform: gpio
    id: output_relay
    pin:
      number: 26

binary_sensor:

  # Кнопка на плате
  - platform: gpio
    name: "Onboard button"
    id: binary_sensor_onboard_button
    pin:
      number: 0
      inverted: true
    filters:
      - delayed_on: ${debounce_delay}

  # Внешний выключатель
  - platform: gpio
    name: "External switch"
    id: binary_sensor_external_switch
    pin:
      number: 27
      inverted: true
    filters:
      - delayed_on: ${debounce_delay}
