# Sonoff POWR316
# https://sonoff.tech/products/sonoff-pow-origin-smart-power-meter-switch
#
# Управляемые объекты:
#   - Реле         (output_relay)
#   - Светодиод    (output_led)
#   - Кнопка       (binary_sensor_button)
# Неуправляемые объекты:
#   - Статусный светодиод
#   - Ваттметр

substitutions:
  friendly_board_name: "SP316"
  debounce_delay: 30ms

esp32:
  variant: esp32
  framework:
    type: esp-idf

packages:
  # Реле
  output_relay: !include
    file: int/output_relay.yaml
    vars:
      pin:
        number: 13

  # Светодиод
  output_led: !include
    file: int/output_led.yaml
    vars:
      pin:
        number: 18
        inverted: true

  # Кнопка
  binary_sensor_button: !include
    file: int/binary_sensor_button.yaml
    vars:
      pin:
        number: 0
        inverted: true
        ignore_strapping_warning: true

  # Статусный светодиод
  status_led: !include
    file: int/status_led.yaml
    vars:
      pin:
        number: 5
        inverted: true
        ignore_strapping_warning: true

  # Ваттметр
  sensor_cse7766: !include
    file: int/sensor_cse7766.yaml

# UART для ваттметра
uart:
  rx_pin: 16
  baud_rate: 4800
  parity: EVEN
