# Реле (output_relay)
#
# Параметры:
#   pin: (обязательно, Pin Schema): настройки пина (pin.number: null)
#   exposed (опционально, boolean): публиковать расширенную информацию (false)

substitutions:
  pin:
    # null тут для того, чтобы не было варнинга про то,
    # что в exposed_output_relay не определена переменная pin.number,
    # и при этом не задавать настоящий пин
    number: null
  exposed: false
  exposed_output_relay:
    text_sensor:
      # Номер пина, на котором работает реле
      - platform: template
        name: "[ext] Relay Pin"
        icon: mdi:connection
        entity_category: diagnostic
        lambda: 'return {"${pin.number}"};'

output:
  # Реле
  - platform: gpio
    id: output_relay
    pin: ${pin}

packages:
  # Публиковать расширенную информацию только по запросу
  exposed: ${ exposed_output_relay if exposed else {} }
