# Камера (esp32_camera)

substitutions:
  number: 1
  i2c_id: i2c_1
  data_pins: [ 11, 9, 8, 10, 12, 18, 17, 16 ]
  vsync_pin: 6
  href_pin: 7
  external_clock:
    pin: 15
    frequency: 12MHz
  pixel_clock_pin: 13
  power_down_pin: null

  # Опциональный пин power_down_pin
  exposed_power_down_pin:
    esp32_camera:
      power_down_pin: 32

# Камера
esp32_camera:
  id: esp32_camera_${number}
  i2c_id: ${i2c_id}
  data_pins: ${data_pins}
  vsync_pin: ${vsync_pin}
  href_pin: ${href_pin}
  external_clock: ${external_clock}
  pixel_clock_pin: ${pixel_clock_pin}
  frame_buffer_count: 2

packages:
  # Опциональный пин power_down_pin
  power_down_pin: ${ exposed_power_down_pin if power_down_pin else {} }
